var works = [
    {'id':'work1','title':'フローエントリ検索システム','description':'フローエントリを検索し、パケット量をグラフで可視化するシステム。','technology':['Ruby','Ruby on Rails','SQLite3','JavaScript','Highcharts'],
    'images':['imgs/portfolio/packetmonitoring2.png','imgs/portfolio/packetmonitoring1.png','imgs/portfolio/packetmonitoring3.png'],'url':''}, 
    {'id':'work2','title':'利用者端末管理システム','description':'ネットワークを利用する利用者の端末を管理するシステム。','technology':['Ruby','Ruby on Rails','SQLite3','JavaScript','Bootstrap'],
    'images':['imgs/portfolio/terminalControl1.png','imgs/portfolio/terminalControl2.png','imgs/portfolio/terminalControl3.png','imgs/portfolio/terminalControl4.png'],'url':''},
    {'id':'work3','title':'利用者別NAPT',
    'description':'OpenFlowを用いて、外部ネッワークとの通信の際には利用者1人に1つのグローバルIPアドレスに変換され、さらに利用者別に論理的な個別プライベートネットワークを構築するNAPT。トポロジ検出機能(LLDPを使用)と最適経路決定機能(ダイクストラ法を使用)も持つ。',
    'technology':['Ruby','OpenFlow(Trema 0.4.7)'],'images':['imgs/portfolio/personalNapt1.png','imgs/portfolio/personalNapt2.png'],'url':''},
    {'id':'work4','title':'mild_document_replace_tool','description':'開いているサイトの文章をマイルドな文章に置き換えるChrome拡張機能。','technology':['HTML5','JavaScript'],
     'images':['imgs/portfolio/mild_document_replace_tool1.png'],
     'url':''},
    {'id':'work5','title':'電卓','description':'様々なCSSライブラリで電卓を作成したものを一覧にしたサイト','technology':['HTML5','JavaScript'],
    'images':['imgs/portfolio/calculator1.png'],'url':'https://takuyash.github.io/Calculator/Calculator_All.html'}, 
    {'id':'work6','title':'プライベートポートフォリオサイト','description':'個人で作成したシステムをまとめたポートフォリオサイト。','technology':['HTML5','JavaScript'],
    'images':['imgs/portfolio/portfoliosite1.png'],'url':'https://takuyash.github.io/'}, 
    {'id':'work7','title':'SimpleFolderLauncher','description':'Windowsフォルダをそのまま使える、超軽量・超高速フォルダランチャー。Windows の任意のフォルダを “そのままランチャー” として利用できる、 超軽量・超高速・設定不要のフォルダランチャー です。','technology':['C#'],
    'images':['imgs/portfolio/SimpleFolderLauncher1.png'],'url':'https://takuyash.github.io/SimplefolderlauncherSite/index.html'}, 
    {'id':'work8','title':'SimpleFolderLauncherSite','description':'SimpleFolderLauncherの紹介サイトです。','technology':['HTML5'],
    'images':['imgs/portfolio/SimpleFolderLauncherSite1.png'],'url':'https://takuyash.github.io/SimplefolderlauncherSite/index.html'}, 
    {'id':'work9','title':'YearAndMonthprogress','description':'年毎月毎の進捗を可視化するサイト','technology':['HTML5','JavaScript'],
    'images':['imgs/portfolio/YearAndMonthprogress1.png'],'url':'https://takuyash.github.io/YearAndMonthprogress/YearAndMonthprogress.html'}, 
];