var works = [
    {'id':'work1','title':'フローエントリ検索システム','description':'フローエントリを検索し、パケット量をグラフで可視化するシステム。','technology':['Ruby','Ruby on Rails','SQLite3','JavaScript','Highcharts'],
    'images':['imgs/portfolio/packetmonitoring2.png','imgs/portfolio/packetmonitoring1.png','imgs/portfolio/packetmonitoring3.png'],'url':''}, 
    {'id':'work2','title':'情報処理技術者試験カレンダー','description':'情報処理技術者試験までの日数を表示するシステム。','technology':['HTML5','JavaScript'],
     'images':['imgs/portfolio/calender1.png'],
     'url':'https://takuyash.github.io/calendar/'},
    {'id':'work3','title':'利用者端末管理システム','description':'ネットワークを利用する利用者の端末を管理するシステム。','technology':['Ruby','Ruby on Rails','SQLite3','JavaScript','Bootstrap'],
    'images':['imgs/portfolio/terminalControl1.png','imgs/portfolio/terminalControl2.png','imgs/portfolio/terminalControl3.png','imgs/portfolio/terminalControl4.png'],'url':''},
    {'id':'work4','title':'利用者別NAPT',
    'description':'OpenFlowを用いて、外部ネッワークとの通信の際には利用者1人に1つのグローバルIPアドレスに変換され、さらに利用者別に論理的な個別プライベートネットワークを構築するNAPT。トポロジ検出機能(LLDPを使用)と最適経路決定機能(ダイクストラ法を使用)も持つ。',
    'technology':['Ruby','OpenFlow(Trema 0.4.7)'],'images':['imgs/portfolio/personalNapt1.png','imgs/portfolio/personalNapt2.png'],'url':''},
    {'id':'work5','title':'プライベートポートフォリオサイト','description':'個人で作成したシステムをまとめたポートフォリオサイト。','technology':['HTML5','JavaScript','Bootstrap'],
    'images':['imgs/portfolio/portfoliosite1.png','imgs/portfolio/portfoliosite2.png','imgs/portfolio/portfoliosite3.png'],'url':'https://takuyash.github.io/'}, 
    {'id':'work6','title':'カラーピッカー','description':'カラーピッカー。','technology':['HTML5','JavaScript','Bootstrap'],
    'images':['imgs/portfolio/colorPicker1.png'],'url':'https://takuyash.github.io/color-picker/color-picker.html'}, 
    {'id':'work7','title':'mild_document_replace_tool','description':'マイルドな文章に置き換えるChrome拡張機能。','technology':['HTML5','JavaScript'],
     'images':['imgs/portfolio/mild_document_replace_tool1.png'],
     'url':''},
];