var works = [
    {'id':'work1','title':'電卓','description':'様々なCSSライブラリで電卓を作成したものを一覧にしたサイト','technology':['HTML5','JavaScript'],
    'images':['imgs/portfolio/calculator1.png'],'url':'https://takuyash.github.io/Calculator/Calculator_All.html'}, 
    {'id':'work2','title':'プライベートポートフォリオサイト','description':'個人で作成したシステムをまとめたポートフォリオサイト。','technology':['HTML5','JavaScript'],
    'images':['imgs/portfolio/portfoliosite1.png'],'url':'https://takuyash.github.io/'}, 
    {'id':'work3','title':'SimpleFolderLauncher','description':'Windowsフォルダをそのまま使える、超軽量・超高速フォルダランチャー。Windows の任意のフォルダを “そのままランチャー” として利用できる、 超軽量・超高速・設定不要のフォルダランチャー です。','technology':['C#'],
    'images':['imgs/portfolio/SimpleFolderLauncher1.png','imgs/portfolio/SimpleFolderLauncher2.gif','imgs/portfolio/SimpleFolderLauncher3.png'],'url':'https://takuyash.github.io/SimplefolderlauncherSite/index.html'}, 
    {'id':'work4','title':'SimpleFolderLauncherSite','description':'SimpleFolderLauncherの紹介サイトです。','technology':['HTML5'],
    'images':['imgs/portfolio/SimpleFolderLauncherSite1.png'],'url':'https://takuyash.github.io/SimplefolderlauncherSite/index.html'}, 
    {'id':'work5','title':'YearAndMonthprogress','description':'年毎月毎の進捗を可視化するサイト','technology':['HTML5','JavaScript'],
    'images':['imgs/portfolio/YearAndMonthprogress1.png'],'url':'https://takuyash.github.io/YearAndMonthprogress/YearAndMonthprogress.html'}, 
    {'id':'work6','title':'PhraseLauncher','description':'キーボードだけで定型文を整理して管理、超高速入力できる Windows 用定型文入力ツールPhraseLauncher','technology':['C#'],
    'images':['imgs/portfolio/PhraseLauncher1.png','imgs/portfolio/PhraseLauncher2.png'],'url':'https://takuyash.github.io/PhraseLauncherSite/index.html'}, 
    {'id':'work7','title':'PhraseLauncherSite','description':'PhraseLauncherの紹介サイトです。','technology':['HTML5','JavaScript'],
    'images':['imgs/portfolio/PhraseLauncherSite1.png'],'url':'https://takuyash.github.io/PhraseLauncherSite/index.html'}, 
];